# Site settings
title: Icecast
email: webmaster@xiph.org
description: "Icecast is free server software for streaming multimedia."
baseurl: ""
url: "http://icecast.org"
timezone: UTC
include: ["redirect.rules"]

# Build settings
markdown: kramdown
permalink: /news/:title/
highlighter: pygments

#collections:
#    docs:
#        output: true

# Markdown settings
# only change if you know what you are doing
kramdown:
    header_offset: 2
    auto_ids: false

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
    -
        scope:
            path: "docs"
        values:
            layout: "docs"
            product: "Icecast"
    -
        scope:
            path: "ices/docs"
        values:
            layout: "docs"
            product: "IceS"