site_name: Icecast Docs
theme: readthedocs

pages:
- Introduction: index.md
- Basic Setup: basic_setup.md
- Configuration File: config_file.md
- Server Statistics: server_stats.md
- Authentication: auth.md
- Relaying: relaying.md
- Listing in a YellowPage Directory: yp.md
- Admin Interface: admin_interface.md
- Windows Specific: win32.md

markdown_extensions: [def_list, admonition]
plugins: []
